services:
  - type: web
    name: tardigarde-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_APP
        value: run:app
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
