"""add_updated_at_to_fee_payments

Revision ID: 97335887aea2
Revises: ee4284590aa4
Create Date: 2026-02-28 22:38:46.006578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97335887aea2'
down_revision = 'ee4284590aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fee_payments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
