"""add_batch_cost_column

Revision ID: d88bca084046
Revises: 9d50bf83f8bc
Create Date: 2026-02-28 21:25:38.116327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd88bca084046'
down_revision = '9d50bf83f8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_cost', sa.Numeric(precision=10, scale=2), server_default='10000.00', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_column('batch_cost')

    # ### end Alembic commands ###
