"""harden fk indexes and association constraints

Revision ID: f9090b739cd7
Revises: ce8e6cc1905e
Create Date: 2026-02-25 21:28:18.471486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9090b739cd7'
down_revision = 'ce8e6cc1905e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_teachers', schema=None) as batch_op:
        batch_op.create_index('ix_batch_teachers_batch_id', ['batch_id'], unique=False)
        batch_op.create_index('ix_batch_teachers_teacher_id', ['teacher_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('batch_teachers_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('batch_teachers_batch_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])
        batch_op.create_foreign_key(None, 'batches', ['batch_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('teachers_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.create_unique_constraint(batch_op.f('teachers_user_id_key'), ['user_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_batch_id'))

    with op.batch_alter_table('batch_teachers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('batch_teachers_batch_id_fkey'), 'batches', ['batch_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('batch_teachers_teacher_id_fkey'), 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_index('ix_batch_teachers_teacher_id')
        batch_op.drop_index('ix_batch_teachers_batch_id')

    # ### end Alembic commands ###
